### ISSUE TITLE
Agent examples don't work after PR#324 -- cannot import name 'AssistantCallContext'

### ISSUE THREAD

**Issue by jameal-stellar** [livekit/agents#414]
Looks like #324 was merged and renamed AssistantContext to AssistantCallContext. I copied the [new function_calling example](https://github.com/livekit/agents/blob/main/examples/voice-assistant/function_calling.py) and got this error when running:

```from livekit.agents.voice_assistant import AssistantCallContext, VoiceAssistant
ImportError: cannot import name 'AssistantCallContext' from 'livekit.agents.voice_assistant' (/Users/jameal/jameal/sandbox/kitt-agent/venv/lib/python3.9/site-packages/livekit/agents/voice_assistant/__init__.py)
```

I'm assuming there should be a new release in `livekit-agents` to reflect this update but the latest is still 0.7.2. Maybe I'm missing something though because I'm new to the Python ecosystem.

Let me know if I can provide any additional info.

**Comment by davidzhao** [comment]
@jameal-stellar sorry about that. we merged the example updates before the code was released.

For now, please try [this version](https://github.com/livekit/agents/blob/6019c43ac6a60bebdb8437aef11e8ef64042b94b/examples/voice-assistant/function_calling.py) of the example. That should work with 0.7.2

**Comment by theomonnom** [comment]
Hey, livekit-agents v0.8.3 was released with this feature
